language: python

python:
  - 2.7

before_install:
  - sudo apt-get install fuse
  - sudo apt-get install memcached
  - sudo apt-get install mosquitto
  - sudo apt-get install libzmq-dev
  - sudo apt-get install build-essential
  - sudo apt-get install libopencv-dev
  - sudo apt-get install librsync-dev
  - sudo apt-get install libfuse-dev
  - sudo apt-get install libzbar-dev
  - sudo apt-get install lsof
  - sudo apt-get install n2n
  - sudo apt-get install python-all-dev
  - sudo apt-get install python-dbus
  - sudo apt-get install python-gevent
  - sudo apt-get install python-gi-dev
  - sudo apt-get install python-imaging
  - sudo apt-get install python-numpy
  - sudo apt-get install python-opencv
  - sudo apt-get install python-pip
  - sudo apt-get install python-pygame
  - sudo apt-get install python-scipy
  - sudo apt-get install python-zbar
  - sudo apt-get install xvfb
  - sudo pip install pip --upgrade
  - sudo pip install xattr
  - sudo pip install pytz
  - sudo pip install fusepy
  - sudo pip install gensim
  - sudo pip install hash_ring
  - sudo pip install html2text
  - sudo pip install isodate
  - sudo pip install langid
  - sudo pip install netifaces
  - sudo pip install -U nltk
  - sudo pip install psutil
  - sudo pip install pycrypto
  - sudo pip install pynetlinux
  - sudo pip install pypng
  - sudo pip install pyqrcode
  - sudo pip install pyserial
  - sudo pip install python-librsync
  - sudo pip install python-rake
  - sudo pip install pyzmq
  - sudo pip install RestrictedPython
  - sudo pip install stop-words
  - sudo pip install textblob
  - sudo pip install tornado
  - sudo pip install websocket-client
  - sudo pip install wget
  - sudo pip install xattr
  - sudo pip install zerorpc
  - sudo pip install hdfs
  - sudo pip install happybase
  - sudo pip install hash_ring
  - sudo pip install pymongo
  - sudo pip install python-memcached
  - sudo pip install python-inotify==0.6-test
  - sudo pip install snakebite
  - sudo pip install leveldb
  - sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl

services:
  - mongodb

before_script:
  - sudo mongo 127.0.0.1:27017/test --eval 'db.user.update({"user":"test"}, {$set:{"user":"test", "password":"00000000000000000000000000000000", "uid":"00000000000000000000000000000000"}}, true, false)'
  - sleep 5
  - sudo bin/virtdev -s &
  - sleep 5
  - sudo bin/virtdev -e &
  - sleep 10

dist:
  - xenial

script:
  - sudo scripts/test-drivers.sh
