language: python

python:
  - 2.7

before_install:
  - sudo apt-get install bluez
  - sudo apt-get install -y bluetooth
  - sudo apt-get install -y bluez-tools
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y isc-dhcp-server
  - sudo apt-get install -y libbluetooth-dev
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install -y librsync-dev
  - sudo apt-get install -y libfuse-dev
  - sudo apt-get install -y libzbar-dev
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y lsof
  - sudo apt-get install -y n2n
  - sudo apt-get install -y python-all-dev
  - sudo apt-get install -y python-bluez
  - sudo apt-get install -y python-cffi
  - sudo apt-get install -y python-dbus
  - sudo apt-get install -y python-gevent
  - sudo apt-get install -y python-gi-dev
  - sudo apt-get install -y python-imaging
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-opencv
  - sudo apt-get install -y python-pil
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y python-pygame
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y python-zbar
  - sudo apt-get install -y xvfb

install:
  - pip install fusepy
  - pip install gensim
  - pip install hash_ring
  - pip install html2text
  - pip install isodate
  - pip install langid
  - pip install netifaces
  - pip install -U nltk
  - pip install psutil
  - pip install pycrypto
  - pip install pynetlinux
  - pip install pypng
  - pip install pyqrcode
  - pip install pyserial
  - pip install python-librsync
  - pip install python-rake
  - pip install pytz
  - pip install pyzmq
  - pip install RestrictedPython
  - pip install stop-words
  - pip install textblob
  - pip install tornado
  - pip install websocket-client
  - pip install wget
  - pip install xattr
  - pip install zerorpc
  - pip install hdfs
  - pip install happybase
  - pip install hash_ring
  - pip install pymongo
  - pip install python-memcached
  - pip install python-inotify==0.6-test
  - pip install snakebite
  - pip install sophia
  - pip install leveldb

script:
  - ARCH=`arch`
  - if [ $ARCH = "armv7l" ]; then
  -   TF_BINARY_URL=https://github.com/samjabrahams/tensorflow-on-raspberry-pi/raw/master/bin/tensorflow-0.9.0-cp27-none-linux_armv7l.whl
  -   pip install --upgrade $TF_BINARY_URL
  - fi
  - if [ $ARCH = "x86_64" ]; then
  -   TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl
  -   pip install --upgrade $TF_BINARY_URL
  - fi
