language: python

python:
  - 2.7

before_install:
  - sudo apt-get install -y fuse
  - sudo apt-get install -y memcached
  - sudo apt-get install -y mosquitto
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libopencv-dev
  - sudo apt-get install -y librsync-dev
  - sudo apt-get install -y libfuse-dev
  - sudo apt-get install -y libzbar-dev
  - sudo apt-get install -y lsof
  - sudo apt-get install -y n2n
  - sudo apt-get install -y python-all-dev
  - sudo apt-get install -y python-dbus
  - sudo apt-get install -y python-gevent
  - sudo apt-get install -y python-gi-dev
  - sudo apt-get install -y python-imaging
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-opencv
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y python-pygame
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y python-zbar
  - sudo apt-get install -y xvfb
  - sudo pip install pip --upgrade
  - sudo pip install xattr
  - sudo pip install pytz
  - sudo pip install fusepy
  - sudo pip install gensim
  - sudo pip install hash_ring
  - sudo pip install html2text
  - sudo pip install isodate
  - sudo pip install langid
  - sudo pip install netifaces
  - sudo pip install -U nltk
  - sudo pip install psutil
  - sudo pip install pycrypto
  - sudo pip install pynetlinux
  - sudo pip install pypng
  - sudo pip install pyqrcode
  - sudo pip install pyserial
  - sudo pip install python-librsync
  - sudo pip install python-rake
  - sudo pip install pyzmq
  - sudo pip install RestrictedPython
  - sudo pip install stop-words
  - sudo pip install textblob
  - sudo pip install tornado
  - sudo pip install websocket-client
  - sudo pip install wget
  - sudo pip install xattr
  - sudo pip install zerorpc
  - sudo pip install hdfs
  - sudo pip install happybase
  - sudo pip install hash_ring
  - sudo pip install pymongo
  - sudo pip install python-memcached
  - sudo pip install python-inotify==0.6-test
  - sudo pip install snakebite
  - sudo pip install leveldb
  - sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl

services:
  - mongodb

before_script:
  - sudo mongo 127.0.0.1:27017/test --eval 'db.user.update({"user":"user"}, {$set:{"user":"user", "password":"00000000000000000000000000000000", "uid":"00000000000000000000000000000000"}}, true, false)'
  - sudo bin/virtdev -s &
  - sleep 5
  - sudo bin/virtdev -e &
  - sleep 5

dist:
  - xenial

script:
  - sudo scripts/test-drivers.sh
