language: python

python:
  - 2.7

before_install:
  - sudo apt-get install bluez
  - sudo apt-get install bluetooth
  - sudo apt-get install bluez-tools
  - sudo apt-get install build-essential
  - sudo apt-get install isc-dhcp-server
  - sudo apt-get install libbluetooth-dev
  - sudo apt-get install libopencv-dev
  - sudo apt-get install librsync-dev
  - sudo apt-get install libfuse-dev
  - sudo apt-get install libzbar-dev
  - sudo apt-get install lsof
  - sudo apt-get install n2n
  - sudo apt-get install python-all-dev
  - sudo apt-get install python-bluez
  - sudo apt-get install python-dbus
  - sudo apt-get install python-gevent
  - sudo apt-get install python-gi-dev
  - sudo apt-get install python-imaging
  - sudo apt-get install python-numpy
  - sudo apt-get install python-opencv
  - sudo apt-get install python-pip
  - sudo apt-get install python-pygame
  - sudo apt-get install python-scipy
  - sudo apt-get install python-zbar
  - sudo apt-get install xvfb

install:
  - easy_install xattr
  - easy_install pytz
  - pip install fusepy
  - pip install gensim
  - pip install hash_ring
  - pip install html2text
  - pip install isodate
  - pip install langid
  - pip install netifaces
  - pip install -U nltk
  - pip install psutil
  - pip install pycrypto
  - pip install pynetlinux
  - pip install pypng
  - pip install pyqrcode
  - pip install pyserial
  - pip install python-librsync
  - pip install python-rake
  - pip install pyzmq
  - pip install RestrictedPython
  - pip install stop-words
  - pip install textblob
  - pip install tornado
  - pip install websocket-client
  - pip install wget
  - pip install xattr
  - pip install zerorpc
  - pip install hdfs
  - pip install happybase
  - pip install hash_ring
  - pip install pymongo
  - pip install python-memcached
  - pip install python-inotify==0.6-test
  - pip install snakebite
  - pip install leveldb
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl

services:
  - mongodb

dist:
  - trusty

before_script:
  - sleep 5
  - bin/virtdev -s &
  - sleep 5
  - bin/virtdev -e &

script:
  - scripts/test-drivers.sh
