#!/bin/sh
apt-get install -y n2n
apt-get install -y bluez
apt-get install -y blueman
apt-get install -y bluetooth
apt-get install -y bluez-utils
apt-get install -y bluez-compat
apt-get install -y python-bluez
apt-get install -y build-essential
apt-get install -y isc-dhcp-server
apt-get install -y libbluetooth-dev
apt-get install -y libopencv-dev
apt-get install -y librsync-dev
apt-get install -y libzbar-dev
apt-get install -y libzmq-dev
apt-get install -y python-pip
apt-get install -y python-pil
apt-get install -y python-dbus
apt-get install -y python-cffi
apt-get install -y python-numpy
apt-get install -y python-gevent
apt-get install -y python-gi-dev
apt-get install -y python-all-dev
apt-get install -y python-imaging
apt-get install -y python-pygame
apt-get install -y python-opencv
apt-get install -y python-zbar
pip install fusepy
pip install hash_ring
pip install html2text
pip install isodate
pip install netifaces
pip install psutil
pip install pycrypto
pip install pypng
pip install pyqrcode
pip install pyserial
pip install python-librsync
pip install pyzmq
pip install RestrictedPython
pip install textblob
pip install wget
pip install xattr
pip install zerorpc
pip install pytz
pip install python-rake
pip install pynetlinux
pip install tornado
pip install websocket-client
