#!/usr/bin/python
import os
import sys
import commands

_name = commands.getoutput('readlink -f %s' % sys.argv[0])
_path = os.path.dirname(_name)
sys.path.append(_path)

from lib.mount import mount

if __name__ == '__main__':
    mount()
